# vim:ft=ansible:
- name: create machine
  hosts: localhost
  gather_facts: no
  tags: create

  tasks:
  - docker_machine:
      name: test-machine-generic
      state: present
      driver: generic
      generic_ip_address: "1.2.3.4"
      generic_ssh_user: "ubuntu"
  - docker_machine:
      name: test-machine2
      state: present
      driver: virtualbox
      virtualbox_memory: "2048"
      virtualbox_cpu_count: "2"
